import { MD3LightTheme } from "react-native-paper";

export const colors = {
  background: "#ffffff",
  surface: "#f8f9ff",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#eff3ff",
  surfaceContainer: "#e6eeff",
  surfaceContainerHigh: "#dde9ff",
  surfaceContainerHighest: "#d4e3ff",

  onBackground: "#0b1c31",
  onSurface: "#0b1c31",
  onSurfaceVariant: "#474556",

  text: "#0b1c31",
  label: "#273951",
  muted: "#64748d",

  primary: "#3904e7",
  onPrimary: "#ffffff",
  primaryContainer: "#533afd",
  onPrimaryContainer: "#ddd9ff",
  primarySoft: "#e3dfff",
  primaryBorder: "#c5c0ff",

  secondary: "#4d6079",
  onSecondary: "#ffffff",
  secondaryContainer: "#cee1ff",
  onSecondaryContainer: "#51647d",

  tertiary: "#960038",
  onTertiary: "#ffffff",
  tertiaryContainer: "#c2004b",
  onTertiaryContainer: "#ffd2d7",

  outline: "#777588",
  outlineVariant: "#c8c4da",
  border: "#e5edf5",

  inverseSurface: "#213147",
  inverseOnSurface: "#ebf1ff",
  inversePrimary: "#c5c0ff",

  surfaceTint: "#5036fa",

  error: "#ba1a1a",
  onError: "#ffffff",
  errorContainer: "#ffdad6",
  onErrorContainer: "#93000a",

  success: "#15be53",
  successText: "#108c3d",
  successSoft: "rgba(21, 190, 83, 0.16)",

  warning: "#9b6829",
  warningSoft: "rgba(155, 104, 41, 0.1)",

  brandDark: "#1c1e54",
  magenta: "#f96bee",
  magentaSoft: "#ffd7ef",

  shadowAmbient: "rgba(23, 23, 23, 0.08)",
  shadowElevated: "rgba(50, 50, 93, 0.25)",
  shadowBlue: "rgba(50, 50, 93, 0.25)",
  shadowSoft: "rgba(23, 23, 23, 0.08)",

  danger: "#ea2261",
  dangerSoft: "#fff0f5",
};

export const appPaperTheme = {
  ...MD3LightTheme,
  roundness: 4,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    onPrimary: colors.onPrimary,
    primaryContainer: colors.primaryContainer,
    onPrimaryContainer: colors.onPrimaryContainer,
    secondary: colors.secondary,
    onSecondary: colors.onSecondary,
    secondaryContainer: colors.secondaryContainer,
    onSecondaryContainer: colors.onSecondaryContainer,
    tertiary: colors.tertiary,
    onTertiary: colors.onTertiary,
    tertiaryContainer: colors.tertiaryContainer,
    onTertiaryContainer: colors.onTertiaryContainer,
    background: colors.background,
    onBackground: colors.onBackground,
    surface: colors.surface,
    onSurface: colors.onSurface,
    surfaceVariant: colors.surfaceContainerLow,
    onSurfaceVariant: colors.onSurfaceVariant,
    outline: colors.outline,
    outlineVariant: colors.outlineVariant,
    error: colors.error,
    errorContainer: colors.errorContainer,
    onErrorContainer: colors.onErrorContainer,
    inverseSurface: colors.inverseSurface,
    inverseOnSurface: colors.inverseOnSurface,
    inversePrimary: colors.inversePrimary,
    surfaceTint: colors.surfaceTint,
    shadow: colors.shadowBlue,
  },
  fonts: {
    displayLarge: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: -0.96,
      fontSize: 48,
      lineHeight: 52,
    },
    displayMedium: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: -0.64,
      fontSize: 32,
      lineHeight: 36,
    },
    displaySmall: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: -0.64,
      fontSize: 32,
      lineHeight: 36,
    },
    headlineLarge: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: -0.64,
      fontSize: 32,
      lineHeight: 36,
    },
    headlineMedium: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: -0.26,
      fontSize: 26,
      lineHeight: 32,
    },
    headlineSmall: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: -0.22,
      fontSize: 22,
      lineHeight: 28,
    },
    titleLarge: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: -0.22,
      fontSize: 22,
      lineHeight: 28,
    },
    titleMedium: {
      fontFamily: "System",
      fontWeight: "400" as const,
      letterSpacing: 0,
      fontSize: 16,
      lineHeight: 24,
    },
    titleSmall: {
      fontFamily: "System",
      fontWeight: "400" as const,
      letterSpacing: 0.1,
      fontSize: 14,
      lineHeight: 20,
    },
    bodyLarge: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: 0,
      fontSize: 16,
      lineHeight: 24,
    },
    bodyMedium: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: 0,
      fontSize: 14,
      lineHeight: 20,
    },
    bodySmall: {
      fontFamily: "System",
      fontWeight: "300" as const,
      letterSpacing: 0,
      fontSize: 12,
      lineHeight: 16,
    },
    labelLarge: {
      fontFamily: "System",
      fontWeight: "400" as const,
      letterSpacing: 0,
      fontSize: 14,
      lineHeight: 20,
    },
    labelMedium: {
      fontFamily: "System",
      fontWeight: "400" as const,
      letterSpacing: 0,
      fontSize: 12,
      lineHeight: 16,
    },
    labelSmall: {
      fontFamily: "System",
      fontWeight: "400" as const,
      letterSpacing: 0,
      fontSize: 11,
      lineHeight: 16,
    },
  },
};

export type AppPaperTheme = typeof appPaperTheme;