import { MD3LightTheme } from "react-native-paper";

export const colors = {
  background: "#ffffff",
  surface: "#ffffff",
  surfaceSoft: "#f6f9fc",
  text: "#061b31",
  label: "#273951",
  muted: "#64748d",
  primary: "#533afd",
  primaryHover: "#4434d4",
  primaryDeep: "#2e2b8c",
  primarySoft: "#ece9ff",
  primaryBorder: "#b9b9f9",
  border: "#e5edf5",
  brandDark: "#1c1e54",
  danger: "#ea2261",
  dangerSoft: "#fff0f5",
  warning: "#9b6829",
  success: "#15be53",
  successText: "#108c3d",
  successSoft: "rgba(21, 190, 83, 0.16)",
  magenta: "#f96bee",
  magentaSoft: "#ffd7ef",
  shadowBlue: "rgba(50, 50, 93, 0.25)",
  shadowSoft: "rgba(23, 23, 23, 0.08)",
};

export const appPaperTheme = {
  ...MD3LightTheme,
  roundness: 4,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary,
    onPrimary: "#ffffff",
    primaryContainer: colors.primarySoft,
    onPrimaryContainer: colors.primaryDeep,
    secondary: colors.primaryDeep,
    secondaryContainer: colors.primarySoft,
    tertiary: colors.magenta,
    background: colors.background,
    onBackground: colors.text,
    surface: colors.surface,
    onSurface: colors.text,
    surfaceVariant: colors.surfaceSoft,
    onSurfaceVariant: colors.muted,
    outline: colors.border,
    outlineVariant: colors.border,
    error: colors.danger,
    errorContainer: colors.dangerSoft,
    onErrorContainer: colors.danger,
  },
  fonts: {
    ...MD3LightTheme.fonts,
    displayLarge: { ...MD3LightTheme.fonts.displayLarge, fontWeight: "300" as const, letterSpacing: -1.4 },
    displayMedium: { ...MD3LightTheme.fonts.displayMedium, fontWeight: "300" as const, letterSpacing: -0.96 },
    headlineLarge: { ...MD3LightTheme.fonts.headlineLarge, fontWeight: "300" as const, letterSpacing: -0.64 },
    headlineMedium: { ...MD3LightTheme.fonts.headlineMedium, fontWeight: "300" as const, letterSpacing: -0.26 },
    titleLarge: { ...MD3LightTheme.fonts.titleLarge, fontWeight: "300" as const, letterSpacing: -0.22 },
    bodyLarge: { ...MD3LightTheme.fonts.bodyLarge, fontWeight: "300" as const },
    bodyMedium: { ...MD3LightTheme.fonts.bodyMedium, fontWeight: "300" as const },
    labelLarge: { ...MD3LightTheme.fonts.labelLarge, fontWeight: "400" as const },
  },
};

export type AppPaperTheme = typeof appPaperTheme;
