/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin/orders`; params?: Router.UnknownInputParams; } | { pathname: `/admin/products`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/customer/addresses`; params?: Router.UnknownInputParams; } | { pathname: `/customer/cart`; params?: Router.UnknownInputParams; } | { pathname: `/customer/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/customer/orders`; params?: Router.UnknownInputParams; } | { pathname: `/customer/product`; params?: Router.UnknownInputParams; } | { pathname: `/customer/profile`; params?: Router.UnknownInputParams; } | { pathname: `/customer/shop`; params?: Router.UnknownInputParams; } | { pathname: `/seller/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/seller/orders`; params?: Router.UnknownInputParams; } | { pathname: `/seller/product-form`; params?: Router.UnknownInputParams; } | { pathname: `/seller/products`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/products`; params?: Router.UnknownOutputParams; } | { pathname: `/admin/users`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/addresses`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/cart`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/product`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/customer/shop`; params?: Router.UnknownOutputParams; } | { pathname: `/seller/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/seller/orders`; params?: Router.UnknownOutputParams; } | { pathname: `/seller/product-form`; params?: Router.UnknownOutputParams; } | { pathname: `/seller/products`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/admin/dashboard${`?${string}` | `#${string}` | ''}` | `/admin/orders${`?${string}` | `#${string}` | ''}` | `/admin/products${`?${string}` | `#${string}` | ''}` | `/admin/users${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/customer/addresses${`?${string}` | `#${string}` | ''}` | `/customer/cart${`?${string}` | `#${string}` | ''}` | `/customer/checkout${`?${string}` | `#${string}` | ''}` | `/customer/orders${`?${string}` | `#${string}` | ''}` | `/customer/product${`?${string}` | `#${string}` | ''}` | `/customer/profile${`?${string}` | `#${string}` | ''}` | `/customer/shop${`?${string}` | `#${string}` | ''}` | `/seller/dashboard${`?${string}` | `#${string}` | ''}` | `/seller/orders${`?${string}` | `#${string}` | ''}` | `/seller/product-form${`?${string}` | `#${string}` | ''}` | `/seller/products${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/admin/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/admin/orders`; params?: Router.UnknownInputParams; } | { pathname: `/admin/products`; params?: Router.UnknownInputParams; } | { pathname: `/admin/users`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/customer/addresses`; params?: Router.UnknownInputParams; } | { pathname: `/customer/cart`; params?: Router.UnknownInputParams; } | { pathname: `/customer/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/customer/orders`; params?: Router.UnknownInputParams; } | { pathname: `/customer/product`; params?: Router.UnknownInputParams; } | { pathname: `/customer/profile`; params?: Router.UnknownInputParams; } | { pathname: `/customer/shop`; params?: Router.UnknownInputParams; } | { pathname: `/seller/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/seller/orders`; params?: Router.UnknownInputParams; } | { pathname: `/seller/product-form`; params?: Router.UnknownInputParams; } | { pathname: `/seller/products`; params?: Router.UnknownInputParams; };
    }
  }
}
